---
title: "Gov 50 Final Project"
author: Jada Pierre
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

This dataset from New York's City Council. Data.gov states "This report denotes statistics for recommended special education services by primary program and related services categorized by students who are fully, partially or not receiving services. The statistics are aggregated by program type, superintendent, district and school."

```{r}
library(tidyverse)
library(dplyr)
ccreport2021 <- read_csv("ccreport2021.csv")
ccreport2021
```

```{r}
ccreport2021 <- ccreport2021 |>
  rename(primpprogramtype = `Primary Program Type`,
         fully_receiving = `Fully Receiving`,
         fully_receivingperc = `Percent Fully Receiving`,
         partially_receiving = `Partially Receiving`,
         partially_receivingperc = `Percent Partially Receiving`,
         not_receiving = `Not Receiving`,
         not_receivingperc = `Percent Not Receiving`) |>
  filter(primpprogramtype == c("Integrated Co-Teaching Services", "SETSS", "Special Class"))
ccreport2021
```

```{r}
ccreport2021 |>
  ggplot(mapping = aes(x = primpprogramtype,
                     y = fully_receivingperc)) +
  geom_col() +
  labs(x = "Primary Program Type",
       y = "Fully Receiving Percent",
       title = "Percent of Fully Receiving Students per Program")
```


```{r}
ccreport2021 |>
  ggplot(mapping = aes(x = primpprogramtype,
                     y = partially_receivingperc)) +
  geom_col() +
  labs(x = "Primary Program Type",
       y = "Partially Receiving Percent",
       title = "Percent of Partially Receiving Students per Program")
```


```{r}
ccreport2021 |>
  ggplot(mapping = aes(x = primpprogramtype,
                     y = not_receivingperc)) +
  geom_col() +
  labs(x = "Primary Program Type",
       y = "Not Receiving Percent",
       title = "Percent of Not Receiving Students per Program")
```

